// src/Education.tsx
import React from "react";
import Section from "./Section";
import { faGraduationCap } from "@fortawesome/free-solid-svg-icons";

type EducationData = {
  schools: {
    name: string;
    location: string;
    image: {
      src: string;
      width: number;
    };
    website: string;
    major: string;
    duration: {
      start: {
        month: string;
        year: number;
      };
      end?: {
        month: string;
        year: number;
      };
    };
    awards: string[];
  }[];
};

function Education(data: EducationData) {
  const { schools } = data;
  return (
    <Section className="education" label="Education" icon={faGraduationCap}>
      {schools.map((school) => (
        <div>
          <img src={school.image.src} alt={school.name} width={school.image.width} />
          <p className="summary">
            <a href={school.website}>
              <strong>{school.name}</strong>
            </a>{" "}
            | <strong>{school.location}</strong> | <em>{school.major}</em>
          </p>
          <p className="duration">
            📅 {school.duration.start.month} {school.duration.start.year} → {school.duration.end ? `${school.duration.end.month} ${school.duration.end.year}` : "Present"}
          </p>
          <ul>
            {school.awards.map((award) => (
              <li>{award}</li>
            ))}
          </ul>
        </div>
      ))}
    </Section>
  );
}

export { Education, EducationData };

// src/components/Education.svelte
<script lang="ts">
	import Section from './Section.svelte';

	import type { Education } from '../types/Education';
	import type { Section as SectionData } from '../types/Section';

	const sectionData: SectionData = {
		className: 'education',
		label: 'Education',
		icon: 'graduation-cap'
	};

	export let data: Education;

	const { institutions } = data;
</script>

<Section data={sectionData}>
	{#each institutions as institution}
		{@const { image, name, url, location, major, duration, awards } = institution}

		{@const { src, width } = image}
		{@const { city, state } = location}
		{@const { start, end } = duration}

		{@const locationText = `${city}, ${state}`}

		<div class="instance">
			<img {src} alt={name} {width} />
			<p class="info">
				<a href={url}>
					<strong>{name}</strong>
				</a>
				| <strong>{locationText}</strong> | <em>{major}</em>
			</p>
			<p class="duration">
				<i class="fa-solid fa-calendar"></i>
				{start.month}
				{start.year} → {#if end}
					{end.month} {end.year}
				{:else}
					Present
				{/if}
			</p>
			<ul>
				{#each awards as award}
					<li>{award}</li>
				{/each}
			</ul>
		</div>
	{/each}
</Section>
