// src/Profile.tsx
import { faEnvelope, faPhone } from "@fortawesome/free-solid-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React from "react";

type Profile = {
  name: string;
  occupation: string;
  phone: string;
  email: string;
  github: string;
  image: string;
};

function Profile(data: Profile) {
  const { name, occupation, phone, email, github, image } = data;
  return (
    <div className="profile">
      <img src={image} alt={name} />
      <div>
        <p className="roboto-bold name">{name}</p>
        <p className="occupation">
          <em>{occupation}</em>
        </p>
        <p className="phone">
          <FontAwesomeIcon icon={faPhone} style={{ marginRight: "8px" }} />
          <a href={`tel:+1${phone.replace(/[^0-9.]/, "")}`}>{phone}</a>
        </p>
        <p className="email">
          <FontAwesomeIcon icon={faEnvelope} style={{ marginRight: "8px" }} />
          <a href={`mailto:${email}`}>{email}</a>
        </p>
        <p className="github">
          <FontAwesomeIcon icon={faGithub} style={{ marginRight: "8px" }} />
          <a href={`https://github.com/${github}`}>{github}</a>
        </p>
      </div>
    </div>
  );
}

export { Profile };

// src/components/Profile.svelte
<script lang="ts">
	import type { Profile } from '../types/Profile';

	export let data: Profile;

	const { image, name, occupation, phone, email, github } = data;

	const { src } = image;
	const { first, last } = name;
	const { title } = occupation;
	const { number } = phone;
	const { address } = email;
	const { username } = github;

	const fullName = `${first} ${last}`;

	const callLink = `tel:+1${number.replace(/[^0-9.]/, '')}`;
	const emailLink = `mailto:${address}`;
	const githubLink = `https://github.com/${username}`;
</script>

<div class="profile">
	<img {src} alt={fullName} />
	<div class="info">
		<p class="name">{fullName}</p>
		<p class="occupation"><em>{title}</em></p>
		<p class="phone">
			<i class="fa-solid fa-phone"></i>
			<a href={callLink}>{number}</a>
		</p>
		<p class="email">
			<i class="fa-solid fa-envelope"></i>
			<a href={emailLink}>{address}</a>
		</p>
		<p class="github">
			<i class="fa-brands fa-github"></i>
			<a href={githubLink}>{username}</a>
		</p>
	</div>
</div>
