// src/components/EmploymentHistory.svelte
<script lang="ts">
	import Section from './Section.svelte';

	import type { EmploymentHistory } from '../types/EmploymentHistory';
	import type { Section as SectionData } from '../types/Section';

	const sectionData: SectionData = {
		className: 'employment-history',
		label: 'Employment History',
		icon: 'handshake'
	};

	export let data: EmploymentHistory;

	const { employments } = data;
</script>

<Section data={sectionData}>
	{#each employments as employment}
		{@const { company, position, duration, skills } = employment}

		{@const { image, name, url, location } = company}

		{@const { src, width } = image}
		{@const { city, state } = location}

		{@const { start, end } = duration}

		{@const locationText = `${city}, ${state}`}

		<div class="instance">
			<img {src} alt={name} {width} />
			<p class="info">
				<a href={url}>
					<strong>{name}</strong>
				</a>
				| <strong>{locationText}</strong> | <em>{position}</em>
			</p>
			<p class="duration">
				<i class="fa-solid fa-calendar"></i>
				{start.month}
				{start.year} → {#if end}
					{end.month} {end.year}
				{:else}
					Present
				{/if}
			</p>
			<ul>
				{#each skills as skill}
					<li>{skill}</li>
				{/each}
			</ul>
		</div>
	{/each}
</Section>

// src/EmploymentHistory.tsx
import React from "react";
import Section from "./Section";
import { faHandshake } from "@fortawesome/free-solid-svg-icons";

type EmploymentHistoryData = {
  employments: {
    company: {
      name: string;
      location: string;
      image: {
        src: string;
        width: number;
      };
      website: string;
    };
    position: string;
    duration: {
      start: {
        month: string;
        year: number;
      };
      end?: {
        month: string;
        year: number;
      };
    };
    skills: string[];
  }[];
};

function EmploymentHistory(data: EmploymentHistoryData) {
  const { employments } = data;
  return (
    <Section className="employment-history" label="Employment History" icon={faHandshake}>
      {employments.map((employment) => (
        <div>
          <img src={employment.company.image.src} alt={employment.company.name} width={employment.company.image.width} />
          <p className="summary">
            <a href={employment.company.website}>
              <strong>{employment.company.name}</strong>
            </a>{" "}
            | <strong>{employment.company.location}</strong> | <em>{employment.position}</em>
          </p>
          <p className="duration">
            📅 {employment.duration.start.month} {employment.duration.start.year} → {employment.duration.end ? `${employment.duration.end.month} ${employment.duration.end.year}` : "Present"}
          </p>
          <ul>
            {employment.skills.map((skill) => (
              <li>{skill}</li>
            ))}
          </ul>
        </div>
      ))}
    </Section>
  );
}

export { EmploymentHistory, EmploymentHistoryData };
