// src/components/Resume.svelte
<script lang="ts">
	import Profile from './Profile.svelte';
	import Skills from './Skills.svelte';
	import EmploymentHistory from './EmploymentHistory.svelte';

	import type { Resume } from '../types/Resume';
	import Education from './Education.svelte';

	export let data: Resume;

	const { profile, skills, employmentHistory, education } = data;
</script>

<div class="resume">
	<Profile data={profile} />
	<Skills texts={skills} />
	<EmploymentHistory data={employmentHistory} />
	<Education data={education} />
</div>

// src/Resume.tsx
import React from "react";
import { Profile } from "./Profile";
import { EmploymentHistory, EmploymentHistoryData } from "./EmploymentHistory";
import { Education, EducationData } from "./Education";
import Skills from "./Skills";

type Resume = {
  profile: Profile;
  skills: string[];
  employmentHistory: EmploymentHistoryData;
  education: EducationData;
};

function Resume(data: Resume) {
  const { education, profile, employmentHistory, skills } = data;
  return (
    <div className="resume">
      <Profile {...profile} />
      <Skills texts={skills} />
      <EmploymentHistory {...employmentHistory} />
      <Education {...education} />
    </div>
  );
}

export { Resume };
