// src/components/Skills.svelte
<script lang="ts">
  import Section from "./Section.svelte";
  import type { Section as SectionData } from "../types/Section";

  export let texts: string[];

  const sectionData: SectionData = {
    className: "skills",
    label: "Skills",
    icon: "screwdriver-wrench",
  };
</script>

<Section data={sectionData}>
  <p>Experienced in:</p>
  <ul>
    {#each texts as text}
      <li>{text}</li>
    {/each}
  </ul>
</Section>

// src/Skills.tsx
import React from "react";
import Section from "./Section";
import { faScrewdriverWrench } from "@fortawesome/free-solid-svg-icons";

export default function Skills(props: { texts: string[] }) {
  const { texts } = props;
  return (
    <Section className="skills" label="Skills" icon={faScrewdriverWrench}>
      <p>Experienced in:</p>
      <ul>
        {texts.map((text) => (
          <li>{text}</li>
        ))}
      </ul>
    </Section>
  );
}
